config/routes.rb
Rails.application.routes.draw do

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions

  get 'pages/about'
  get 'pages/bottling'
  get 'pages/groves'
  get 'pages/varieties'
  get 'pages/harvesting'
  get 'pages/mill'
  get 'pages/quality'
  get 'pages/contact'

  namespace :media do
    resources :videos, only: [:index, :show]
    resources :albums, only: [:index, :show]
    resources :assets, only: [:index, :show]
    get 'download/:id' => 'assets#download', as: :download
    root 'albums#index'
  end

  namespace :blog do
    resources :posts, only: [:index, :show]
    root 'posts#index'
  end

  namespace :dashboard do
    resources :assets, path: 'downloads'
    resources :videos
    resources :albums
    resources :posts
    resources :products
    resources :categories
    resources :recipes
    resources :uses
    root 'posts#index'
  end

  resources :categories, only: [:index, :show]
  resources :products, only: [:index]
  resources :recipes, only: [:index, :show]
  resources :uses, only: [:index, :show]

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  root 'pages#home'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id                   :integer          not null, primary key
#  name                 :string(255)
#  body                 :text
#  created_at           :datetime
#  updated_at           :datetime
#  published            :boolean          default(FALSE), not null
#  published_at         :datetime
#  picture_file_name    :string(255)
#  picture_content_type :string(255)
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#  source               :text
#

class Post < ActiveRecord::Base

  has_attached_file :picture, :styles => { :large => "500x500>", :medium => "300x300>", :thumb => "131x131>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  validates :name, :body, :picture, presence: true

  include Slugalicious
  slugged :name

  scope :published, -> { where(published: true) }
  
  before_save :check_published_post

  def check_published_post
    if self.published == true
     self.published_at = Time.now
    end
  end
end

app/controllers/blog/posts_controller.rb
class Blog::PostsController < ApplicationController

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.published.order('published_at desc')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find_from_slug(params[:id])
  end

end

app/controllers/dashboard/posts_controller.rb
class Dashboard::PostsController < ApplicationController
  before_filter :authorize
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  layout 'dashboard'

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to dashboard_post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to dashboard_post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_from_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :body, :published, :picture, :source)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blog/posts/index.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">  
  <%= render partial: "shared/navbar" %>
</div>

<div id="blog">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="posts">
          <% @posts.each do |post| %>
            <div class="post-item">
              <h2>
                <small class="pull-right">
                  Published at <br>
                  <span class="date"><%= post.published_at.strftime("%d/%m/%Y") %></span>
                </small>
                <%= link_to post.name, blog_post_path(post) %>
              </h2>
              <div class="thumbnail">
                <%= image_tag post.picture.url(:large) %>
              </div>
              
              <%=h raw HTML_Truncator.truncate(post.body, 60) %>

              <%= link_to t('buttons.more'), blog_post_path(post), class: 'btn btn-default pull-right', style: 'margin-top: 20px;' %>
              <span class="clearfix"></span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/blog/posts/show.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">  
  <%= render partial: "shared/navbar" %>
</div>

<div id="blog">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="posts">

          <div class="post-item">
            <h1><%= @post.name %></h1>
            <div class="thumbnail">
              <%= image_tag @post.picture.url(:large) %>
            </div>
            <p><%= raw @post.body %></p>
            
            <% if @post.source %>
              <p class="source"><i><b>Source:</b> <%= @post.source %></i></p>
            <% end %>

            <div class="sharer">
              <ul class="list-inline">
                <li><a href="https://www.facebook.com/sharer/sharer.php?u=<%= request.original_url %>" class="btn btn-default" target="_blank"><i class="fa fa-facebook"></i> Share on Facebook</a></li>
                <li><a href="https://twitter.com/home?status=<%= request.original_url %>" class="btn btn-default" target="_blank"><i class="fa fa-twitter"></i> Share on Twitter</a></li>
                <li><a href="https://plus.google.com/share?url=<%= request.original_url %>" class="btn btn-default" target="_blank"><i class="fa fa-google-plus"></i> Share on Google Plus</a></li>
              </ul>
            </div>

          </div>

        </div>
      </div>
    </div>
  </div>
</div>