config/routes.rb
Rails.application.routes.draw do

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions

  get 'pages/about'
  get 'pages/bottling'
  get 'pages/groves'
  get 'pages/varieties'
  get 'pages/harvesting'
  get 'pages/mill'
  get 'pages/quality'
  get 'pages/contact'

  namespace :media do
    resources :videos, only: [:index, :show]
    resources :albums, only: [:index, :show]
    resources :assets, only: [:index, :show]
    get 'download/:id' => 'assets#download', as: :download
    root 'albums#index'
  end

  namespace :blog do
    resources :posts, only: [:index, :show]
    root 'posts#index'
  end

  namespace :dashboard do
    resources :assets, path: 'downloads'
    resources :videos
    resources :albums
    resources :posts
    resources :products
    resources :categories
    resources :recipes
    resources :uses
    root 'posts#index'
  end

  resources :categories, only: [:index, :show]
  resources :products, only: [:index]
  resources :recipes, only: [:index, :show]
  resources :uses, only: [:index, :show]

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  root 'pages#home'
end

app/views/shared/_dashboard_navbar.html.erb
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to image_tag("logo.png"), root_path, class: 'navbar-brand' %>
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse" id="navbar-main">
        <div class="navbar-right">
          <p class="navbar-text">Logged in as <%= current_user.email %>.</p>
          <% if current_user %>
            <%= link_to "Log Out", logout_path, class: 'btn btn-default navbar-btn' %>
          <% end %>

          <ul class="nav navbar-nav">
            <li class="<%= active_lang('fr') %>"><%= link_to 'FR', change_locale_path(:fr) %></li>
            <li class="<%= active_lang('en') %>"><%= link_to 'EN', change_locale_path(:en) %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">

      <div class="col-sm-6 col-xs-12">
        <p>© Copyright MEDFLAVOUR 2015 | Powered by <a href="http://appid.tn/fr/">APPID</a></p>
      </div>

      <div class="col-sm-6 col-xs-12">
        <ul class="list-inline social pull-right">
          <li><a href="https://www.facebook.com/pages/Oleiva/141869862652385" target="_blank"><i class="fa fa-facebook fa-lg"></i></a></li>
        </ul>
      </div>

    </div>
  </div>
</footer>

app/views/shared/_media_navbar.html.erb
<nav class="navbar navbar-default navbar-lower" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#media-navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse collapse-buttons"  id="media-navbar">
      <ul class="nav navbar-nav">
        <%= active_link_to 'Albums', media_albums_path, :wrap_tag => :li %>
        <%= active_link_to 'Videos', media_videos_path, :wrap_tag => :li %>
        <%= active_link_to t('menu.media.download'), media_assets_path, :wrap_tag => :li %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
    <%= link_to image_tag("logo.png"), root_path, class: 'navbar-brand pull-left' %>
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse" id="navbar-main">

        <ul class="nav navbar-nav">
          <%= active_link_to t('menu.main.about'), pages_about_path, :wrap_tag => :li %>
          <%= active_link_to 'Portfolio', categories_path, id: 'portfolio-menu', :wrap_tag => :li %>
          <%= active_link_to 'Media', media_root_path, :wrap_tag => :li %>
          <%= active_link_to 'Blog', blog_root_path, :wrap_tag => :li %>
          <%= active_link_to 'Contact', pages_contact_path, :wrap_tag => :li %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if false %>
            <li class="hidden-xs hidden-sm"><%= link_to 'Dashboard', dashboard_root_path %></li>
          <% end %>
          <li class="<%= active_lang('fr') %>"><%= link_to 'FR', change_locale_path(:fr) %></li>
          <li class="<%= active_lang('en') %>"><%= link_to 'EN', change_locale_path(:en) %></li>
        </ul>

      </div>
    </div>