config/routes.rb
Rails.application.routes.draw do

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions

  get 'pages/about'
  get 'pages/bottling'
  get 'pages/groves'
  get 'pages/varieties'
  get 'pages/harvesting'
  get 'pages/mill'
  get 'pages/quality'
  get 'pages/contact'

  namespace :media do
    resources :videos, only: [:index, :show]
    resources :albums, only: [:index, :show]
    resources :assets, only: [:index, :show]
    get 'download/:id' => 'assets#download', as: :download
    root 'albums#index'
  end

  namespace :blog do
    resources :posts, only: [:index, :show]
    root 'posts#index'
  end

  namespace :dashboard do
    resources :assets, path: 'downloads'
    resources :videos
    resources :albums
    resources :posts
    resources :products
    resources :categories
    resources :recipes
    resources :uses
    root 'posts#index'
  end

  resources :categories, only: [:index, :show]
  resources :products, only: [:index]
  resources :recipes, only: [:index, :show]
  resources :uses, only: [:index, :show]

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  root 'pages#home'
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Album < ActiveRecord::Base
  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true, reject_if: proc { |attributes| attributes['description'].blank? }

  validates_presence_of :title

  validate :must_have_one_photo
 
  def must_have_one_photo
    errors.add(:photos, 'must have one photo') if photos_empty?
  end

  def photos_empty?
    photos.empty? or photos.all? {|photo| photo.marked_for_destruction? }
  end

  def self.featured_image(album)
    album.photos.where(featured: true).first ? album.photos.where(featured: true).first : album.photos.first
  end
end

app/controllers/dashboard/albums_controller.rb
class Dashboard::AlbumsController < ApplicationController
  before_filter :authorize
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  layout 'dashboard'
  
  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to dashboard_album_url(@album), notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to dashboard_album_url(@album), notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, photos_attributes: [:id, :featured, :description, :asset, :_destroy])
    end
end

app/controllers/media/albums_controller.rb
class Media::AlbumsController < ApplicationController

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])
  end

end

app/controllers/media/assets_controller.rb
class Media::AssetsController < ApplicationController

  # GET /assets
  # GET /assets.json
  def index
    @assets = Asset.all
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
    @asset = Asset.find(params[:id])
  end

  def download
    @asset = Asset.find(params[:id])
    send_file @asset.download.path,
              :filename => @asset.download_file_name,
              :type => @asset.download_content_type,
              :disposition => 'attachment'
  end

end

app/controllers/media/videos_controller.rb
class Media::VideosController < ApplicationController

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/media/albums/index.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">  
  <%= render partial: "shared/navbar" %>
</div>
<%= render partial: "shared/media_navbar" %>

<div id="albums">
  <div class="container">
    <div class="items">

      <% @albums.each_with_index do |album, index| %>
        <div class="item row no-gutters product">

          <div class="col-sm-7 <%= first_block_class(index) %> col-xs-12">
            <%= image_tag Album.featured_image(album).asset.url, class: 'img-responsive' %>
          </div>
          <div class="col-sm-5 description <%= second_block_class(index) %> col-xs-12">
            <div class="inner">
              <h2><%= album.title %></h2>
              <%= link_to t('buttons.browse'), media_album_path(album), class: 'btn btn-default' %>
            </div>
          </div>

        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/media/albums/show.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">  
  <%= render partial: "shared/navbar" %>
</div>
<%= render partial: "shared/media_navbar" %>

<div id="album">
  <div class="container">
    <h2><%= @album.title %></h2>

    <div class="row">
    <% @album.photos.each do |photo| %>
      <div class="col-xs-12 col-sm-6">
        <div class="photo">
          <%= image_tag photo.asset.url, class: 'img-responsive photo-asset' %>
          <div class="caption">
            
            <p class="pull-left"><%= photo.description.capitalize %></p>
            
            <ul class="list-inline pull-right">
              <li><a href="https://www.facebook.com/sharer/sharer.php?u=<%= request.original_url %>" target="_blank"><i class="fa fa-facebook"></i></a></li>
              <li><a href="https://twitter.com/home?status=<%= request.original_url %>" target="_blank"><i class="fa fa-twitter"></i></a></li>
              <li><a href="https://plus.google.com/share?url=<%= request.original_url %>" target="_blank"><i class="fa fa-google-plus"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>