config/routes.rb
Rails.application.routes.draw do

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions

  get 'pages/about'
  get 'pages/bottling'
  get 'pages/groves'
  get 'pages/varieties'
  get 'pages/harvesting'
  get 'pages/mill'
  get 'pages/quality'
  get 'pages/contact'

  namespace :media do
    resources :videos, only: [:index, :show]
    resources :albums, only: [:index, :show]
    resources :assets, only: [:index, :show]
    get 'download/:id' => 'assets#download', as: :download
    root 'albums#index'
  end

  namespace :blog do
    resources :posts, only: [:index, :show]
    root 'posts#index'
  end

  namespace :dashboard do
    resources :assets, path: 'downloads'
    resources :videos
    resources :albums
    resources :posts
    resources :products
    resources :categories
    resources :recipes
    resources :uses
    root 'posts#index'
  end

  resources :categories, only: [:index, :show]
  resources :products, only: [:index]
  resources :recipes, only: [:index, :show]
  resources :uses, only: [:index, :show]

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  root 'pages#home'
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id                             :integer          not null, primary key
#  name                           :string(255)
#  parent_id                      :integer
#  lft                            :integer          not null
#  rgt                            :integer          not null
#  short_description              :text
#  long_description               :text
#  portfolio_picture_file_name    :string(255)
#  portfolio_picture_content_type :string(255)
#  portfolio_picture_file_size    :integer
#  portfolio_picture_updated_at   :datetime
#  banner_picture_file_name       :string(255)
#  banner_picture_content_type    :string(255)
#  banner_picture_file_size       :integer
#  banner_picture_updated_at      :datetime
#  products_picture_file_name     :string(255)
#  products_picture_content_type  :string(255)
#  products_picture_file_size     :integer
#  products_picture_updated_at    :datetime
#  logo_file_name                 :string(255)
#  logo_content_type              :string(255)
#  logo_file_size                 :integer
#  logo_updated_at                :datetime
#

class Category < ActiveRecord::Base
  acts_as_nested_set
  has_many :products

  has_attached_file :logo, :styles => { :medium => "250x250>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

  has_attached_file :products_picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :products_picture, :content_type => /\Aimage\/.*\Z/

  has_attached_file :portfolio_picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :portfolio_picture, :content_type => /\Aimage\/.*\Z/

  has_attached_file :banner_picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :banner_picture, :content_type => /\Aimage\/.*\Z/

  validates :name, presence: true

  translates :name, :short_description, :long_description
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end
end

app/controllers/dashboard/categories_controller.rb
class Dashboard::CategoriesController < ApplicationController
  before_filter :authorize
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  layout 'dashboard'

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to dashboard_categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: dashboard_categories_url }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to dashboard_categories_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: dashboard_categories_url }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :parent_id, :short_description, :long_description, :portfolio_picture, :banner_picture, :products_picture, :logo)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">  
  <%= render partial: "shared/navbar" %>
</div>

<div id="portfolio">

  <nav class="second-nav hidden-xs">
    <div class="container">
      <ul class="list-inline" role="tablist" id="filters">
        <li role="presentation" class="active"><a data-filter="*" href="#" data-toggle="tab"><%= t('menu.portfolio.all') %></a></li>
        <li role="presentation"><a data-filter=".product" href="#" data-toggle="tab"><%= t('menu.portfolio.products') %></a></li>
        <li role="presentation"><a data-filter=".how" href="#" data-toggle="tab"><%= t('menu.portfolio.know_how') %></a></li>
        <li role="presentation"><a data-filter=".uses" href="#" data-toggle="tab"><%= t('menu.portfolio.uses') %></a></li>
      </ul>
    </div>
  </nav>

  <div class="container">
    <div class="portfolio-items">

      <!-- Products -->
      <% @categories.each_with_index do |category, index| %>
        <div class="item row no-gutters product">

          <div class="col-sm-7 <%= first_block_class(index) %> col-xs-12">
            <%= image_tag category.portfolio_picture.url, class: 'img-responsive' %>
          </div>
          <div class="col-sm-5 description <%= second_block_class(index) %> col-xs-12">
            <div class="inner">
              <%= image_tag category.logo.url(:medium), class: 'img-responsive' %>
              <p><%= category.short_description %></p>
              <%= link_to t('buttons.more'), category_path(category), class: 'btn btn-default' %>
            </div>
          </div>

        </div>
      <% end %>

      <!-- bottling -->
      <div class="item row no-gutters how">
        <div class="col-sm-7 col-xs-12">
          <%= image_tag 'portfolio/bottling.jpg', class: 'img-responsive' %>
        </div>
        <div class="col-sm-5 description col-xs-12">
          <div class="inner">
            <h2><%= t('portfolio.bottling.title') %></h3>
            <p><%= t('portfolio.bottling.short') %></p>
            <%= link_to t('buttons.more'), pages_bottling_path, class: 'btn btn-default' %>
          </div>
        </div>
      </div>

      <!-- groves -->
      <div class="item row no-gutters how">
        <div class="col-sm-7 col-sm-push-5 col-xs-12">
          <%= image_tag 'portfolio/groves.png', class: 'img-responsive' %>
        </div>
        <div class="col-sm-5 col-sm-pull-7 description col-xs-12">
          <div class="inner">
            <h2><%= t('portfolio.groves.title') %></h2>
            <p><%= t('portfolio.groves.text') %></p>
            <%= link_to t('buttons.more'), pages_groves_path, class: 'btn btn-default' %>
          </div>
        </div>
      </div>

      <!-- varieties -->
      <div class="item row no-gutters how">
        <div class="col-sm-7 col-xs-12">
          <%= image_tag 'portfolio/varieties.jpg', class: 'img-responsive' %>
        </div>
        <div class="col-sm-5 description col-xs-12">
          <div class="inner">
            <h2><%= t('portfolio.varieties.title') %></h2>
            <p><%= t('portfolio.varieties.short')%></p>
            <%= link_to t('buttons.more'), pages_varieties_path, class: 'btn btn-default' %>
          </div>
        </div>
      </div>

      <!-- harvesting -->
      <div class="item row no-gutters how">
        <div class="col-sm-7 col-sm-push-5 col-xs-12">
          <%= image_tag 'portfolio/harvesting.png', class: 'img-responsive' %>
        </div>
        <div class="col-sm-5 col-sm-pull-7 description col-xs-12">
          <div class="inner">
            <h2><%= t('harvesting.title') %></h2>
            <p><%= t('portfolio.harvesting.short') %></p>
            <%= link_to t('buttons.more'), pages_harvesting_path, class: 'btn btn-default' %>
          </div>
        </div>
      </div>

      <!-- mill -->
      <div class="item row no-gutters how">
        <div class="col-sm-7 col-xs-12">
          <%= image_tag 'portfolio/mill.png', class: 'img-responsive' %>
        </div>
        <div class="col-sm-5 description col-xs-12">
          <div class="inner">
            <h2><%= t('mill.title') %></h2>
            <p><%= t('portfolio.mill.short') %></p>
            <%= link_to t('buttons.more'), pages_mill_path, class: 'btn btn-default' %>
          </div>
        </div>
      </div>

      <!-- quality -->
      <div class="item row no-gutters how">
        <div class="col-sm-7 col-sm-push-5 col-xs-12">
          <%= image_tag 'portfolio/quality.png', class: 'img-responsive' %>
        </div>
        <div class="col-sm-5 col-sm-pull-7 description col-xs-12">
          <div class="inner">
            <h2><%= t('quality.title') %></h2>
            <p><%= t('portfolio.quality.short') %></p>
            <%= link_to t('buttons.more'), pages_quality_path, class: 'btn btn-default' %>
          </div>
        </div>
      </div>
      
      <!-- recipes -->
      <div class="item row no-gutters uses">
        <div class="col-sm-7 col-xs-12">
          <%= image_tag 'portfolio/recipes.png', class: 'img-responsive' %>
        </div>
        <div class="col-sm-5 description col-xs-12">
          <div class="inner">
            <h2>Mediterranean recipes</h2>
            <p><%= t('portfolio.recipes.short') %></p>
            <%= link_to t('buttons.more'), recipes_path, class: 'btn btn-default' %>
          </div>
        </div>
      </div>

      <% if false %>

      <!-- uses -->
      <div class="item row no-gutters uses">
        <div class="col-sm-5 description col-xs-12">
          <div class="inner">
            <h2>Other uses</h2>
            <p>Pendant des années, l’huile d’olive tunisienne, par sa production abondante et sa qualité supérieure, a été exportée dans le </p>
            <%= link_to t('buttons.more'), uses_path, class: 'btn btn-default' %>
          </div>
        </div>
        <div class="col-sm-7 col-xs-12">
          <%= image_tag 'portfolio/uses.png', class: 'img-responsive' %>
        </div>
      </div>

      <% end %>

    </div>
  </div>

</div>

<script>
  var $container = $('.portfolio-items').imagesLoaded( function() {
    $container.isotope({
      itemSelector: '.item'
    });
  });
  
  // filter items on button click
  $('#filters').on( 'click', 'li > a', function() {
    var filterValue = $(this).attr('data-filter');
    $container.isotope({ filter: filterValue });
  });
</script>

app/views/categories/show.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">  
  <%= render partial: "shared/navbar" %>
</div>

<div id="category">
  <div class="header">
    <div class="container-fluid">
      <%= image_tag @category.banner_picture.url, class: "img-responsive" %>
    </div>
  </div>

  <div class="content">
    <div class="container">
      <h1><%= @category.name %></h1>
      <p><%= raw(@category.long_description) %></p>

      <div class="certif">
        <%= image_tag 'kosher.png' %>
      </div>
      
      <%= link_to products_path(category_id: @category.id), class: 'prods-link' do %>
        
        <%= image_tag @category.products_picture.url, class: "img-responsive" %>
        
        <p>
          <span>More details</span>
        </p>

        <div class="caption">
          <span><%= @category.name %> products</span>
        </div>

      <% end %>
    </div>
  </div>
</div>